# Generated by Django 4.2.23 on 2025-07-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the project title', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief summary of the project')),
                ('live_link', models.URLField(blank=True, help_text='Enter the live link of the project', null=True)),
                ('code_link', models.URLField(blank=True, help_text='Enter the code link of the project', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which the project should be displayed')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the project', upload_to='projects/images/')),
                ('alt_text', models.CharField(blank=True, help_text='Enter a alt text for the image', max_length=200, null=True)),
                ('project', models.ForeignKey(help_text='Select the project this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myport.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Select technologies used in the project', related_name='projects', to='myport.technology'),
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Enter a description for the featured project', max_length=500)),
                ('project', models.ForeignKey(help_text='Select the project to feature', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myport.project')),
            ],
            options={
                'verbose_name': 'Featured Project',
                'verbose_name_plural': 'Featured Projects',
            },
        ),
    ]
