# Generated by Django 4.2.23 on 2025-07-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='project',
            name='code_link',
            field=models.URLField(blank=True, help_text='The URL to the source code on GitHub.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Projects with a lower number will appear first.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='The URL to the live demo.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(help_text='A short summary of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Select the technologies used for this project.', related_name='projects', to='myport.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='The title of the project.', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, default=1, help_text='Alt text for the image, for accessibility.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Upload a screenshot for the project.', upload_to='project_screenshots/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myport.project'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='FeaturedProject',
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myport.project'),
        ),
    ]
