# Generated by Django 4.2.23 on 2025-07-22 01:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0002_feature_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Upload a profile image for the developer.', max_length=255, verbose_name='developer_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image, for accessibility.', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload a screenshot for the project.', max_length=255, verbose_name='project_screenshots/'),
        ),
    ]
